//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICACION
    {
        public int IDCERTIFICACION { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public short IDAREACONOCIMIENTO { get; set; }
        public string DESCRIPCIONCERTIFICACION { get; set; }
        public string TITULOCERTIFICACION { get; set; }
        public System.DateTime FECHAINICIOCERTIFICACION { get; set; }
        public System.DateTime FECHAFINCERTIFICACION { get; set; }
        public string CODIGOCERTIFICACION { get; set; }
        public string INSTITUCION { get; set; }
    
        public virtual AREA_CONOCIMIENTO AREA_CONOCIMIENTO { get; set; }
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
