//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICACION
    {
        public int IDCERTIFICACION { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public short IDAREACONOCIMIENTO { get; set; }
        public string DESCRIPCIONCERTIFICACION { get; set; }
        public string TITULOCERTIFICACION { get; set; }
        public System.DateTime FECHAINICIOCERTIFICACION { get; set; }
        public System.DateTime FECHAFINCERTIFICACION { get; set; }
        public string CODIGOCERTIFICACION { get; set; }
        public string INSTITUCION { get; set; }
    
        public virtual AREA_CONOCIMIENTO AREA_CONOCIMIENTO { get; set; }
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
