//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public decimal IDCONTACTO { get; set; }
        public int IDPOSTULANTE { get; set; }
        public short IDTIPOCONTACTO { get; set; }
        public string VINCULO { get; set; }
    
        public virtual POSTULANTE POSTULANTE { get; set; }
        public virtual TIPO_CONTACTO TIPO_CONTACTO { get; set; }
    }
}
