//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRICULUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURRICULUM()
        {
            this.CERTIFICACION = new HashSet<CERTIFICACION>();
            this.EXPERIENCIALABORAL = new HashSet<EXPERIENCIALABORAL>();
            this.FORMACIONACADEMICA = new HashSet<FORMACIONACADEMICA>();
            this.HABILIDAD = new HashSet<HABILIDAD>();
            this.IDIOMA = new HashSet<IDIOMA>();
            this.LOGRO = new HashSet<LOGRO>();
            this.PARTICIPACION_PROFESIONAL = new HashSet<PARTICIPACION_PROFESIONAL>();
            this.PUBLICACION = new HashSet<PUBLICACION>();
            this.REFERENCIA = new HashSet<REFERENCIA>();
        }
    
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICACION> CERTIFICACION { get; set; }
        public virtual POSTULANTE POSTULANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPERIENCIALABORAL> EXPERIENCIALABORAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMACIONACADEMICA> FORMACIONACADEMICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABILIDAD> HABILIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDIOMA> IDIOMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGRO> LOGRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTICIPACION_PROFESIONAL> PARTICIPACION_PROFESIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICACION> PUBLICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERENCIA> REFERENCIA { get; set; }
    }
}
