//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------//

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CIVIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_CIVIL()
        {
            this.POSTULANTE = new HashSet<POSTULANTE>();
        }
    
        public short IDESTADOCIVIL { get; set; }

        [DisplayName("Estado Civil")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(20,ErrorMessage ="no más de 20 caracteres")]
        public string NOMBREESTADOCIVIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULANTE> POSTULANTE { get; set; }
    }
}
