//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CIVIL_POSTULANTE_MM
    {
        public int IDPOSTULANTE { get; set; }
        public short IDESTADOCIVIL { get; set; }
        public Nullable<System.DateTime> FECHACAMBIO { get; set; }
        public Nullable<short> ACTIVO { get; set; }
    
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual POSTULANTE POSTULANTE { get; set; }
    }
}
