//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMEN()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
        }
    
        public int CODIGOEMPRESA { get; set; }
        public short ACTIVO { get; set; }
        public decimal PONDERACION { get; set; }
        public int CODIGOEXAMEN { get; set; }
        public Nullable<int> IDTIPOEXAMEN { get; set; }
        public string DESCRIPCIONEXAMEN { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPO_EXAMEN TIPO_EXAMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
    }
}
