//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMEN()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
        }
    
        public int CODIGOEMPRESA { get; set; }
        public short ACTIVO { get; set; }
        public decimal PONDERACION { get; set; }
        public int CODIGOEXAMEN { get; set; }
        public Nullable<int> IDTIPOEXAMEN { get; set; }
        public string DESCRIPCIONEXAMEN { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPO_EXAMEN TIPO_EXAMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
    }
}
