//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERIENCIALABORAL
    {
        public int IDEXPERIENCIALABORAL { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public Nullable<int> IDCARGO { get; set; }
        public string INSTITUCION { get; set; }
        public string TITULOPROYECTO { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHAFIN { get; set; }
        public string NUMEROCONTACTOORG { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
