
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FORMACIONACADEMICA
{

    public int IDFORMACION { get; set; }

    public int IDCURRICULUM { get; set; }

    public int IDPOSTULANTE { get; set; }

    public int IDTIPOFORMACION { get; set; }

    public string INSTITUCION { get; set; }

    public string TITULO { get; set; }

    public System.DateTime FECHAINICIOFORMACION { get; set; }

    public System.DateTime FECHAFINFORMACION { get; set; }

    public bool FORMAL { get; set; }

    public bool GRADOACADEMICO { get; set; }



    public virtual CURRICULUM CURRICULUM { get; set; }

    public virtual TIPOFORMACINONACADEMICA TIPOFORMACINONACADEMICA { get; set; }

}

}
