//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCION_PLAZA
    {
        public int IDFUNCION { get; set; }
        public Nullable<int> IDPLAZA { get; set; }
        public string DESCRIPCIONPLAZA { get; set; }
    
        public virtual PLAZA PLAZA { get; set; }
    }
}
