//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCION_PLAZA
    {
        public int IDFUNCION { get; set; }
        public Nullable<int> IDPLAZA { get; set; }
        public string DESCRIPCIONPLAZA { get; set; }
    
        public virtual PLAZA PLAZA { get; set; }
    }
}
