
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HABILIDAD
{

    public int IDHABILIDAD { get; set; }

    public int IDCURRICULUM { get; set; }

    public int IDPOSTULANTE { get; set; }

    public int IDTIPOHABILIDAD { get; set; }

    public string NOMBREHABILIDAD { get; set; }



    public virtual CURRICULUM CURRICULUM { get; set; }

    public virtual TIPO_HABILIDAD TIPO_HABILIDAD { get; set; }

}

}
