//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABILIDAD
    {
        public decimal IDHABILIDAD { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public int IDTIPOHABILIDAD { get; set; }
        public string NOMBREHABILIDAD { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
        public virtual TIPO_HABILIDAD TIPO_HABILIDAD { get; set; }
    }
}
