
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IDIOMA
{

    public int IDIDIOMA { get; set; }

    public Nullable<int> IDCURRICULUM { get; set; }

    public Nullable<int> IDPOSTULANTE { get; set; }

    public string NOMBREIDIOMA { get; set; }

    public Nullable<bool> LENGUAMATERNA { get; set; }

    public string ESCRITURA { get; set; }

    public string LECTURA { get; set; }

    public string CONVERSACION { get; set; }

    public string ESCUCHA { get; set; }



    public virtual CURRICULUM CURRICULUM { get; set; }

}

}
