//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDIOMA
    {
        public int IDIDIOMA { get; set; }
        public Nullable<int> IDCURRICULUM { get; set; }
        public Nullable<int> IDPOSTULANTE { get; set; }
        public string NOMBREIDIOMA { get; set; }
        public Nullable<bool> LENGUAMATERNA { get; set; }
        public string ESCRITURA { get; set; }
        public string LECTURA { get; set; }
        public string CONVERSACION { get; set; }
        public string ESCUCHA { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
