//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGRO
    {
        public int IDLOGRO { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public string TITULOLOGRO { get; set; }
        public Nullable<System.DateTime> FECHALOGRO { get; set; }
        public string OTORGANTELOGRO { get; set; }
        public string DESCRIPCIONLOGRO { get; set; }
        public Nullable<bool> PREMIO { get; set; }
        public Nullable<bool> LABORSOCIAL { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
