//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logro
    {
        public int idLogro { get; set; }
        public string tituloLogro { get; set; }
        public Nullable<System.DateTime> fechaLogro { get; set; }
        public string otorganteLogro { get; set; }
        public string descripcionLogro { get; set; }
    }
}
