

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ConexionBDBolsa : DbContext
{
    public ConexionBDBolsa()
        : base("name=ConexionBDBolsa")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AREA_CONOCIMIENTO> AREA_CONOCIMIENTO { get; set; }

    public virtual DbSet<CERTIFICACION> CERTIFICACION { get; set; }

    public virtual DbSet<CONTACTO> CONTACTO { get; set; }

    public virtual DbSet<CURRICULUM> CURRICULUM { get; set; }

    public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }

    public virtual DbSet<EMPRESA> EMPRESA { get; set; }

    public virtual DbSet<ESTADO_CIVIL> ESTADO_CIVIL { get; set; }

    public virtual DbSet<EXPERIENCIALABORAL> EXPERIENCIALABORAL { get; set; }

    public virtual DbSet<FORMACIONACADEMICA> FORMACIONACADEMICA { get; set; }

    public virtual DbSet<HABILIDAD> HABILIDAD { get; set; }

    public virtual DbSet<IDIOMA> IDIOMA { get; set; }

    public virtual DbSet<LOGRO> LOGRO { get; set; }

    public virtual DbSet<MENU> MENU { get; set; }

    public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }

    public virtual DbSet<NIVEL_IDIOMA> NIVEL_IDIOMA { get; set; }

    public virtual DbSet<PAIS> PAIS { get; set; }

    public virtual DbSet<PARTICIPACION_PROFESIONAL> PARTICIPACION_PROFESIONAL { get; set; }

    public virtual DbSet<POSTULANTE> POSTULANTE { get; set; }

    public virtual DbSet<POSTULANTE_TIPO_DOCUMENTO_MM> POSTULANTE_TIPO_DOCUMENTO_MM { get; set; }

    public virtual DbSet<PUBLICACION> PUBLICACION { get; set; }

    public virtual DbSet<REFERENCIA> REFERENCIA { get; set; }

    public virtual DbSet<ROL> ROL { get; set; }

    public virtual DbSet<ROL_USUARIO_MM> ROL_USUARIO_MM { get; set; }

    public virtual DbSet<TELEFONO> TELEFONO { get; set; }

    public virtual DbSet<TIPO_CONTACTO> TIPO_CONTACTO { get; set; }

    public virtual DbSet<TIPO_DOCUMENTO_IDENTIDAD> TIPO_DOCUMENTO_IDENTIDAD { get; set; }

    public virtual DbSet<TIPO_HABILIDAD> TIPO_HABILIDAD { get; set; }

    public virtual DbSet<TIPO_PARTICIPACION> TIPO_PARTICIPACION { get; set; }

    public virtual DbSet<TIPO_TELEFONO> TIPO_TELEFONO { get; set; }

    public virtual DbSet<TIPOFORMACINONACADEMICA> TIPOFORMACINONACADEMICA { get; set; }

    public virtual DbSet<TIPOREFERENCIA> TIPOREFERENCIA { get; set; }

    public virtual DbSet<USUARIO> USUARIO { get; set; }

}

}

