//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConexionBDBolsa : DbContext
    {
        public ConexionBDBolsa()
            : base("name=ConexionBDBolsa")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA_CARGO> AREA_CARGO { get; set; }
        public virtual DbSet<AREA_CONOCIMIENTO> AREA_CONOCIMIENTO { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CERTIFICACION> CERTIFICACION { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<CURRICULUM> CURRICULUM { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO_CIVIL> ESTADO_CIVIL { get; set; }
        public virtual DbSet<ESTADO_CIVIL_POSTULANTE_MM> ESTADO_CIVIL_POSTULANTE_MM { get; set; }
        public virtual DbSet<EXAMEN> EXAMEN { get; set; }
        public virtual DbSet<EXPERIENCIALABORAL> EXPERIENCIALABORAL { get; set; }
        public virtual DbSet<FORMACIONACADEMICA> FORMACIONACADEMICA { get; set; }
        public virtual DbSet<FUNCION_PLAZA> FUNCION_PLAZA { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<GIRO> GIRO { get; set; }
        public virtual DbSet<HABILIDAD> HABILIDAD { get; set; }
        public virtual DbSet<IDIOMA> IDIOMA { get; set; }
        public virtual DbSet<LOGRO> LOGRO { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual DbSet<NIVEL_IDIOMA> NIVEL_IDIOMA { get; set; }
        public virtual DbSet<OPCION_PREGUNTA> OPCION_PREGUNTA { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PARTICIPACION_PROFESIONAL> PARTICIPACION_PROFESIONAL { get; set; }
        public virtual DbSet<PLAZA> PLAZA { get; set; }
        public virtual DbSet<POSTULANTE> POSTULANTE { get; set; }
        public virtual DbSet<POSTULANTE_PLAZA> POSTULANTE_PLAZA { get; set; }
        public virtual DbSet<POSTULANTE_TIPO_DOCUMENTO_MM> POSTULANTE_TIPO_DOCUMENTO_MM { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTA { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACION { get; set; }
        public virtual DbSet<REFERENCIA> REFERENCIA { get; set; }
        public virtual DbSet<REQUISITO> REQUISITO { get; set; }
        public virtual DbSet<RESPUESTA> RESPUESTA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROL_USUARIO_MM> ROL_USUARIO_MM { get; set; }
        public virtual DbSet<TELEFONO> TELEFONO { get; set; }
        public virtual DbSet<TIPO_CONTACTO> TIPO_CONTACTO { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO_IDENTIDAD> TIPO_DOCUMENTO_IDENTIDAD { get; set; }
        public virtual DbSet<TIPO_EXAMEN> TIPO_EXAMEN { get; set; }
        public virtual DbSet<TIPO_HABILIDAD> TIPO_HABILIDAD { get; set; }
        public virtual DbSet<TIPO_PARTICIPACION> TIPO_PARTICIPACION { get; set; }
        public virtual DbSet<TIPO_REQUISITO> TIPO_REQUISITO { get; set; }
        public virtual DbSet<TIPO_TELEFONO> TIPO_TELEFONO { get; set; }
        public virtual DbSet<TIPOFORMACINONACADEMICA> TIPOFORMACINONACADEMICA { get; set; }
        public virtual DbSet<TIPOPREGUNTA> TIPOPREGUNTA { get; set; }
        public virtual DbSet<TIPOREFERENCIA> TIPOREFERENCIA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<ViewCurriculum> ViewCurriculum { get; set; }
        public virtual DbSet<ViewPlazaGenerica> ViewPlazaGenerica { get; set; }
        public virtual DbSet<ViewPostulante> ViewPostulante { get; set; }
    
        public virtual int cambiarEstadoUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cambiarEstadoUsuario", idParameter);
        }
    
        public virtual int DesbloqueoUsuario(Nullable<int> idUs)
        {
            var idUsParameter = idUs.HasValue ?
                new ObjectParameter("idUs", idUs) :
                new ObjectParameter("idUs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DesbloqueoUsuario", idUsParameter);
        }
    
        public virtual ObjectResult<ObtenerResultados_Result> ObtenerResultados(Nullable<int> codEmp, Nullable<int> idp)
        {
            var codEmpParameter = codEmp.HasValue ?
                new ObjectParameter("codEmp", codEmp) :
                new ObjectParameter("codEmp", typeof(int));
    
            var idpParameter = idp.HasValue ?
                new ObjectParameter("idp", idp) :
                new ObjectParameter("idp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerResultados_Result>("ObtenerResultados", codEmpParameter, idpParameter);
        }
    
        public virtual ObjectResult<USP_CheckCredentials_Result> USP_CheckCredentials(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CheckCredentials_Result>("USP_CheckCredentials", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ValidarUsuario_Result> ValidarUsuario(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidarUsuario_Result>("ValidarUsuario", userNameParameter, passwordParameter);
        }
    }
}
