
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MUNICIPIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MUNICIPIO()
    {

        this.POSTULANTE = new HashSet<POSTULANTE>();

    }


    public int IDMUNICIPIO { get; set; }

    public int IDDEPARTAMENTO { get; set; }

    public string NOMBREMUNICIPIO { get; set; }



    public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<POSTULANTE> POSTULANTE { get; set; }

}

}
