//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_IDIOMA
    {
        public int IDNIVELIDIOMA { get; set; }

        [DisplayName("Nivel Idioma")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string NOMBRENIVELIDIOMA { get; set; }

        [DisplayName("Código de nivel idioma")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public string CODIGONIVELIDIOMA { get; set; }
    }
}
