
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NIVEL_IDIOMA
{

    public int IDNIVELIDIOMA { get; set; }

    public string NOMBRENIVELIDIOMA { get; set; }

    public string CODIGONIVELIDIOMA { get; set; }

}

}
