//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_IDIOMA
    {
        public int IDNIVELIDIOMA { get; set; }
        public string NOMBRENIVELIDIOMA { get; set; }
        public string CODIGONIVELIDIOMA { get; set; }
    }
}
