//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPCION_PREGUNTA()
        {
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }
    
        public string DESCRIPCIONOPCION { get; set; }
        public Nullable<short> PUNTAJE { get; set; }
        public Nullable<short> ORDEN { get; set; }
        public int IDOPCIONPREGUNTA { get; set; }
        public Nullable<int> IDPREGUNTA { get; set; }
    
        public virtual PREGUNTA PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
