//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPCION_PREGUNTA()
        {
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }
    
        public string DESCRIPCIONOPCION { get; set; }
        public Nullable<short> PUNTAJE { get; set; }
        public Nullable<short> ORDEN { get; set; }
        public int IDOPCIONPREGUNTA { get; set; }
        public Nullable<int> IDPREGUNTA { get; set; }
    
        public virtual PREGUNTA PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
