
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PAIS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PAIS()
    {

        this.PARTICIPACION_PROFESIONAL = new HashSet<PARTICIPACION_PROFESIONAL>();

    }


    public int IDPAIS { get; set; }

    public string NOMBREPAIS { get; set; }

    public string CODIGOPAIS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PARTICIPACION_PROFESIONAL> PARTICIPACION_PROFESIONAL { get; set; }

}

}
