//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPACION_PROFESIONAL
    {
        public int IDPARTICIPACION { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public int IDTIPOPARTICIPACION { get; set; }
        public Nullable<int> IDPAIS { get; set; }
        public string TITULOPARTICIPACION { get; set; }
        public string LUGARPARTICIPACION { get; set; }
        public System.DateTime FECHAPARTICIPACION { get; set; }
        public string ANFITRION { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual TIPO_PARTICIPACION TIPO_PARTICIPACION { get; set; }
    }
}
