//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPACION_PROFESIONAL
    {
        public int IDPARTICIPACION { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public int IDTIPOPARTICIPACION { get; set; }
        public Nullable<int> IDPAIS { get; set; }
        public string TITULOPARTICIPACION { get; set; }
        public string LUGARPARTICIPACION { get; set; }
        public System.DateTime FECHAPARTICIPACION { get; set; }
        public string ANFITRION { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual TIPO_PARTICIPACION TIPO_PARTICIPACION { get; set; }
    }
}
