//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAZA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAZA()
        {
            this.FUNCION_PLAZA = new HashSet<FUNCION_PLAZA>();
            this.POSTULANTE_PLAZA = new HashSet<POSTULANTE_PLAZA>();
            this.REQUISITO = new HashSet<REQUISITO>();
        }
    
        public Nullable<int> IDMUNICIPIO { get; set; }
        public Nullable<int> IDGENERO { get; set; }
        public Nullable<int> CODIGOEMPRESA { get; set; }
        public Nullable<float> SALARIO { get; set; }
        public string FORMAPAGO { get; set; }
        public Nullable<short> EDADMIN { get; set; }
        public Nullable<short> EDADMAX { get; set; }
        public Nullable<bool> VEHICULO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public int IDPLAZA { get; set; }
        public Nullable<int> IDCARGO { get; set; }
        public Nullable<short> ANIOSMINIMOXP { get; set; }
        public string DESCRIPCIONPLAZA { get; set; }
        public Nullable<int> VACANTES { get; set; }
        public string TIPOJORNADA { get; set; }
        public byte[] IMAGENPLAZA { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCION_PLAZA> FUNCION_PLAZA { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULANTE_PLAZA> POSTULANTE_PLAZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISITO> REQUISITO { get; set; }
    }
}
