//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTULANTE_PLAZA
    {
        public int IDPLAZA { get; set; }
        public int IDPOSTULANTE { get; set; }
        public Nullable<System.DateTime> FECHAAPLICACION { get; set; }
    
        public virtual PLAZA PLAZA { get; set; }
        public virtual POSTULANTE POSTULANTE { get; set; }
    }
}
