//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTA()
        {
            this.OPCION_PREGUNTA = new HashSet<OPCION_PREGUNTA>();
        }
    
        public Nullable<int> CODIGOEXAMEN { get; set; }
        public string TEXTOPREGUNTA { get; set; }
        public int IDPREGUNTA { get; set; }
        public Nullable<short> IDTIPOOPCION { get; set; }
    
        public virtual EXAMEN EXAMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCION_PREGUNTA> OPCION_PREGUNTA { get; set; }
        public virtual TIPOPREGUNTA TIPOPREGUNTA { get; set; }
    }
}
