//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTA()
        {
            this.OPCION_PREGUNTA = new HashSet<OPCION_PREGUNTA>();
        }
    
        public Nullable<int> CODIGOEXAMEN { get; set; }
        public string TEXTOPREGUNTA { get; set; }
        public int IDPREGUNTA { get; set; }
        public Nullable<short> IDTIPOOPCION { get; set; }
    
        public virtual EXAMEN EXAMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPCION_PREGUNTA> OPCION_PREGUNTA { get; set; }
        public virtual TIPOPREGUNTA TIPOPREGUNTA { get; set; }
    }
}
