//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACION
    {
        public int IDPUBLICACION { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public string TITULOPUBLICACION { get; set; }
        public string EDITORIAL { get; set; }
        public string REVISTA { get; set; }
        public System.DateTime FECHAPUBLICACION { get; set; }
        public string ISBN { get; set; }
        public Nullable<bool> LIBRO { get; set; }
        public string NUMEROEDICION { get; set; }
    
        public virtual CURRICULUM CURRICULUM { get; set; }
    }
}
