//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISITO
    {
        public Nullable<int> IDTIPOREQUISITO { get; set; }
        public string DESCRIPCIONREQUISITO { get; set; }
        public int IDREQUISITO { get; set; }
        public Nullable<int> IDPLAZA { get; set; }
    
        public virtual PLAZA PLAZA { get; set; }
        public virtual TIPO_REQUISITO TIPO_REQUISITO { get; set; }
    }
}
