//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public int IDTELEFONO { get; set; }
        public int IDPOSTULANTE { get; set; }
        public Nullable<short> IDTIPOTELEFONO { get; set; }
        public string NUMEROTELEFONO { get; set; }
    
        public virtual POSTULANTE POSTULANTE { get; set; }
        public virtual TIPO_TELEFONO TIPO_TELEFONO { get; set; }
    }
}
