
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BolsaTrabajoV1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TELEFONO
{

    public int IDTELEFONO { get; set; }

    public int IDPOSTULANTE { get; set; }

    public Nullable<short> IDTIPOTELEFONO { get; set; }

    public string NUMEROTELEFONO { get; set; }



    public virtual POSTULANTE POSTULANTE { get; set; }

    public virtual TIPO_TELEFONO TIPO_TELEFONO { get; set; }

}

}
