//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTO_IDENTIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DOCUMENTO_IDENTIDAD()
        {
            this.POSTULANTE_TIPO_DOCUMENTO_MM = new HashSet<POSTULANTE_TIPO_DOCUMENTO_MM>();
        }
    
        public int IDTIPODOCUMENTOIDENTIDAD { get; set; }
        public string NOMBREDOCUMENTOIDENTIDAD { get; set; }
        public Nullable<short> CANTIDADCARACTERES { get; set; }
        public string MASCARA { get; set; }
        public Nullable<bool> EXTRANJERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSTULANTE_TIPO_DOCUMENTO_MM> POSTULANTE_TIPO_DOCUMENTO_MM { get; set; }
    }
}
