//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PARTICIPACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PARTICIPACION()
        {
            this.PARTICIPACION_PROFESIONAL = new HashSet<PARTICIPACION_PROFESIONAL>();
        }
    
        public int IDTIPOPARTICIPACION { get; set; }
        public string NOMBRETIPOPARTICIPACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTICIPACION_PROFESIONAL> PARTICIPACION_PROFESIONAL { get; set; }
    }
}
