//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPlazaGenerica
    {
        public string cargo { get; set; }
        public string descriplaza { get; set; }
        public Nullable<float> salario { get; set; }
        public Nullable<short> edadmin { get; set; }
        public Nullable<short> edadmax { get; set; }
        public Nullable<int> vacantes { get; set; }
        public Nullable<short> minimoexp { get; set; }
        public string empresa { get; set; }
        public string municipio { get; set; }
        public Nullable<int> idgiroemp { get; set; }
        public int codempresa { get; set; }
        public int iddepart { get; set; }
        public int idplaza { get; set; }
        public int idcargo { get; set; }
        public Nullable<int> idareacargo { get; set; }
        public Nullable<int> idgenero { get; set; }
        public string genero { get; set; }
    }
}
