//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPostulante
    {
        public string genero { get; set; }
        public string nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string municipio { get; set; }
        public Nullable<int> idgenero { get; set; }
        public int idpostulante { get; set; }
        public int iddep { get; set; }
        public int idcu { get; set; }
    }
}
