//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCurriculum
    {
        public string NOMBREHABILIDAD { get; set; }
        public string INSTITUCION { get; set; }
        public string TITULO { get; set; }
        public string NOMBREIDIOMA { get; set; }
        public int IDCURRICULUM { get; set; }
        public int IDPOSTULANTE { get; set; }
        public Nullable<int> IDTIPOHABILIDAD { get; set; }
        public Nullable<int> IDTIPOFORMACION { get; set; }
        public Nullable<short> idacth { get; set; }
        public Nullable<short> idaccr { get; set; }
    }
}
