//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolsaTrabajoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPlazaGenerica
    {
        public int idp { get; set; }
        public Nullable<int> idc { get; set; }
        public Nullable<int> idg { get; set; }
        public Nullable<int> idm { get; set; }
        public string des { get; set; }
        public Nullable<float> sal { get; set; }
        public Nullable<short> emin { get; set; }
        public Nullable<short> emax { get; set; }
        public Nullable<int> vac { get; set; }
        public Nullable<short> mex { get; set; }
        public string emp { get; set; }
        public string car { get; set; }
        public string mun { get; set; }
        public string gen { get; set; }
    }
}
